name: data-extraction
channels:
  - conda-forge
dependencies:
  - python=3.12
  - altair
  - jupyterlab
  - numpy
  - pandas
  - pydash
  - tqdm
  - environs
  - cudatoolkit
  - pip:
    - bitsandbytes
    - torch
    - accelerate
    - lightning
    - transformers
