name: data-extraction
channels:
  - conda-forge
dependencies:
  - python=3.12
  - altair
  - jupyterlab
  - numpy
  - pandas
  - pydash
  - tqdm
  - environs
  - accelerate
  - bitsandbytes
  - pytorch-gpu
  - lightning
  - transformers
