name: data-extraction-bp1
channels:
  - conda-forge
dependencies:
  - python=3.12
  - altair
  - jupyterlab
  - numpy
  - pandas
  - pydash
  - tqdm
  - environs
  - pytorch-gpu
  - just
  - pip:
    - transformers
    - optimum-quanto
    - accelerate
    - lightning
