name: data-extraction
channels:
  - conda-forge
dependencies:
  - python=3.12
  - altair
  - jupyterlab
  - numpy
  - pandas
  - pydash
  - tqdm
  - environs
  - pytorch-gpu
  - pip:
    - transformers
    - optimum
    - optimum-quanto
    - accelerate
    - lightning
