name: data-extraction
channels:
  - conda-forge
dependencies:
  - altair
  - environs
  - jupyterlab
  - just
  - numpy
  - pandas
  - pip
  - pydash
  - python=3.12
  - pytorch-gpu
  - tqdm
  - loguru
  - pip:
    - accelerate==1.4.0
    - compressed-tensors==0.9.4
    - lightning==2.5.0.post0
    - optimum==1.24.0
    - optimum-quanto==0.2.7
    - transformers==4.51.3
    - jsonschema
